-- Active: 1735239549405@@127.0.0.1@5432@add-medical-ac
INSERT INTO AP (
    NUMERO_DE_LA_FACTURA,
    CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD,
    TIPO_DE_IDENTIFICACION_DEL_USUARIO,
    NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA,
    FECHA_DEL_PROCEDIMIENTO,
    NUMERO_DE_AUTORIZACION,
    CODIGO_DEL_PROCEDIMIENTO,
    AMBITO_DE_REALIZACION_DEL_PROCEDIMIENTO,
    FINALIDAD_DEL_PROCEDIMIENTO,
    PERSONAL_QUE_ATIENDE,
    DIAGNOSTICO_PRINCIPAL,
    DIAGNOSTICO_RELACIONADO,
    COMPLICACION,
    FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO,
    VALOR_DEL_PROCEDIMIENTO
)
SELECT DISTINCT
    NUMERO_DE_LA_FACTURA,
    CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD,
    TIPO_DE_IDENTIFICACION_DEL_USUARIO,
    NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA,
    FECHA_DE_LA_CONSULTA AS FECHA_DEL_PROCEDIMIENTO,
    NUMERO_DE_AUTORIZACION,
    CODIGO_DE_LA_CONSULTA AS CODIGO_DEL_PROCEDIMIENTO,
    NULL AS AMBITO_DE_REALIZACION_DEL_PROCEDIMIENTO,
    FINALIDAD_DE_LA_CAUSA_EXTERNA_CONSULTA AS FINALIDAD_DEL_PROCEDIMIENTO,
    NULL AS PERSONAL_QUE_ATIENDE,
    CODIGO_DEL_DIAGNOSTICO_PRINCIPAL AS DIAGNOSTICO_PRINCIPAL,
    CODIGO_DEL_DIAGNOSTICO_RELACIONADO_NO_1 AS DIAGNOSTICO_RELACIONADO,
    NULL AS COMPLICACION,
    NULL AS FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO,
    NULL AS VALOR_DEL_PROCEDIMIENTO
FROM AC
WHERE NOT EXISTS (
    SELECT 1
    FROM AP
    WHERE AP.NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA = AC.NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA
);

