-- Active: 1735239549405@@127.0.0.1@5432@add-medical-ac@public
SELECT 
    AP.DIAGNOSTICO_PRINCIPAL AS CODIGO_DIAGNOSTICO,
    CIE10.NOMBRE AS NOMBRE_ENFERMEDAD,
    COUNT(*) AS FRECUENCIA
FROM 
    AP
JOIN 
    CIE10 ON AP.DIAGNOSTICO_PRINCIPAL = CIE10.CODIGO
GROUP BY 
    AP.DIAGNOSTICO_PRINCIPAL, CIE10.NOMBRE
ORDER BY 
    FRECUENCIA DESC;