INSERT INTO AP (
    NUMERO_DE_LA_FACTURA,
    CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD,
    TIPO_DE_IDENTIFICACION_DEL_USUARIO,
    NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA,
    FECHA_DEL_PROCEDIMIENTO,
    NUMERO_DE_AUTORIZACION,
    CODIGO_DEL_PROCEDIMIENTO,
    AMBITO_DE_REALIZACION_DEL_PROCEDIMIENTO,
    FINALIDAD_DEL_PROCEDIMIENTO,
    PERSONAL_QUE_ATIENDE,
    DIAGNOSTICO_PRINCIPAL,
    DIAGNOSTICO_RELACIONADO,
    COMPLICACION,
    FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO,
    VALOR_DEL_PROCEDIMIENTO
)
SELECT 
    NUMERO_DE_LA_FACTURA,
    CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD,
    TIPO_DE_IDENTIFICACION_DEL_USUARIO,
    NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA,
    FECHA_DEL_PROCEDIMIENTO,
    NUMERO_DE_AUTORIZACION,
    'DI0008-2' AS CODIGO_DEL_PROCEDIMIENTO,
    AMBITO_DE_REALIZACION_DEL_PROCEDIMIENTO,
    FINALIDAD_DEL_PROCEDIMIENTO,
    PERSONAL_QUE_ATIENDE,
    DIAGNOSTICO_PRINCIPAL,
    DIAGNOSTICO_RELACIONADO,
    COMPLICACION,
    FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO,
    VALOR_DEL_PROCEDIMIENTO
FROM AP
WHERE diagnostico_principal IN (
    'E100', 'E101', 'E102', 'E103', 'E104', 'E105', 'E106', 'E107', 'E108', 'E109',
    'E110', 'E111', 'E112', 'E113', 'E114', 'E115', 'E116', 'E117', 'E118', 'E119',
    'E120', 'E121', 'E122', 'E123', 'E124', 'E125', 'E126', 'E127', 'E128', 'E129',
    'E130', 'E131', 'E132', 'E133', 'E134', 'E135', 'E136', 'E137', 'E138', 'E139',
    'E140', 'E141', 'E142', 'E143', 'E144', 'E145', 'E146', 'E147', 'E148', 'E149',
    'E15X', 'O240', 'O241', 'O242', 'O243', 'O244', 'O249'
);

CREATE OR REPLACE FUNCTION create_new_registry(diagnosticos_principales TEXT[], codigos_procedimientos TEXT[])
RETURNS TABLE (
    NUMERO_DE_LA_FACTURA TEXT,
    CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD TEXT,
    TIPO_DE_IDENTIFICACION_DEL_USUARIO TEXT,
    NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA TEXT,
    FECHA_DEL_PROCEDIMIENTO TEXT,
    NUMERO_DE_AUTORIZACION TEXT,
    CODIGO_DEL_PROCEDIMIENTO TEXT,
    AMBITO_DE_REALIZACION_DEL_PROCEDIMIENTO TEXT,
    FINALIDAD_DEL_PROCEDIMIENTO TEXT,
    PERSONAL_QUE_ATIENDE TEXT,
    DIAGNOSTICO_PRINCIPAL TEXT,
    DIAGNOSTICO_RELACIONADO TEXT,
    COMPLICACION TEXT,
    FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO TEXT,
    VALOR_DEL_PROCEDIMIENTO TEXT
) AS $$
DECLARE
    codigo_procedimiento TEXT;
BEGIN
    CREATE TEMP TABLE temp_ap AS TABLE AP WITH NO DATA;

    FOREACH codigo_procedimiento IN ARRAY codigos_procedimientos
    LOOP
        INSERT INTO temp_ap (
            NUMERO_DE_LA_FACTURA,
            CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD,
            TIPO_DE_IDENTIFICACION_DEL_USUARIO,
            NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA,
            FECHA_DEL_PROCEDIMIENTO,
            NUMERO_DE_AUTORIZACION,
            CODIGO_DEL_PROCEDIMIENTO,
            AMBITO_DE_REALIZACION_DEL_PROCEDIMIENTO,
            FINALIDAD_DEL_PROCEDIMIENTO,
            PERSONAL_QUE_ATIENDE,
            DIAGNOSTICO_PRINCIPAL,
            DIAGNOSTICO_RELACIONADO,
            COMPLICACION,
            FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO,
            VALOR_DEL_PROCEDIMIENTO
        )
        SELECT 
            AP.NUMERO_DE_LA_FACTURA,
            AP.CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD,
            AP.TIPO_DE_IDENTIFICACION_DEL_USUARIO,
            AP.NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA,
            AP.FECHA_DEL_PROCEDIMIENTO,
            AP.NUMERO_DE_AUTORIZACION,
            codigo_procedimiento AS CODIGO_DEL_PROCEDIMIENTO,
            AP.AMBITO_DE_REALIZACION_DEL_PROCEDIMIENTO,
            AP.FINALIDAD_DEL_PROCEDIMIENTO,
            AP.PERSONAL_QUE_ATIENDE,
            AP.DIAGNOSTICO_PRINCIPAL,
            AP.DIAGNOSTICO_RELACIONADO,
            AP.COMPLICACION,
            AP.FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO,
            AP.VALOR_DEL_PROCEDIMIENTO
        FROM AP
        WHERE AP.DIAGNOSTICO_PRINCIPAL = ANY(diagnosticos_principales);
    END LOOP;

    RETURN QUERY SELECT * FROM temp_ap;

    DROP TABLE temp_ap;
END;
$$ LANGUAGE plpgsql;