SELECT * FROM actualizar_tipo_identificacion();
SELECT * FROM actualizar_codigo_municipio();
SELECT * FROM actualizar_codigo_departamento();
SELECT * FROM actualizar_codigo_factura('240708');
SELECT * FROM actualizar_finalidad_causa_externa();
SELECT * FROM actualizar_finalidad_causa_externa();
select * from actualizar_finalidad_procedimiento();
select * from eliminar_usuario_y_registros_relacionados('1066478846');
SELECT * FROM actualizar_causa_externa();
SELECT * FROM actualizar_causa_externa_null();
SELECT * FROM actualizar_diagnostico_vacio();
SELECT * FROM actualizar_tipo_diagnostico_principal();
SELECT * FROM actualizar_diagnostico_vacio_ap();
SELECT * FROM actualizar_acto_quirurgico();
SELECT * FROM actualizar_tipo_documento_all('1067821863','PT')
