CREATE OR REPLACE FUNCTION actualizar_finalidad_diagnostico_niños()
RETURNS TABLE (
    numero_de_identificacion_del_usuario_del_sistema VARCHAR,
    edad INTEGER,
    unidad_de_medida_en_la_edad VARCHAR
) AS $$
BEGIN
    RETURN QUERY
    UPDATE AC
    SET FINALIDAD_DE_LA_CAUSA_EXTERNA_CONSULTA = '04', 
        CODIGO_DEL_DIAGNOSTICO_PRINCIPAL = 'Z762'
    FROM US
    WHERE AC.NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA = US.NUMERO_DE_IDENTIFICACION_DEL_USUARIO_DEL_SISTEMA
      AND (
          (US.UNIDAD_DE_MEDIDA_EN_LA_EDAD = '1' AND US.EDAD::INTEGER <= 1) OR
          (US.UNIDAD_DE_MEDIDA_EN_LA_EDAD = '2' AND US.EDAD::INTEGER BETWEEN 0 AND 12) OR
          (US.UNIDAD_DE_MEDIDA_EN_LA_EDAD = '3' AND US.EDAD::INTEGER BETWEEN 0 AND 31)
      )
    RETURNING AC.NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA::VARCHAR, 
              US.EDAD::INTEGER, 
              US.UNIDAD_DE_MEDIDA_EN_LA_EDAD::VARCHAR;
END;
$$ LANGUAGE plpgsql;