CREATE OR REPLACE FUNCTION actualizar_forma_realizacion_acto_quirurgico()
RETURNS void AS $$
BEGIN
    UPDATE AP
    SET FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO = '1'
    WHERE FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO IS NULL OR FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO <> '1';
END;
$$ LANGUAGE plpgsql;