DROP TABLE AP;
CREATE TABLE AP (
        NUMERO_DE_LA_FACTURA TEXT,
        CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD TEXT,
        TIPO_DE_IDENTIFICACION_DEL_USUARIO TEXT,
        NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA TEXT,
        FECHA_DEL_PROCEDIMIENTO TEXT,
        NUMERO_DE_AUTORIZACION TEXT,
        CODIGO_DEL_PROCEDIMIENTO TEXT,
        AMBITO_DE_REALIZACION_DEL_PROCEDIMIENTO TEXT,
        FINALIDAD_DEL_PROCEDIMIENTO TEXT,
        PERSONAL_QUE_ATIENDE TEXT,
        DIAGNOSTICO_PRINCIPAL TEXT,
        DIAGNOSTICO_RELACIONADO TEXT,
        COMPLICACION TEXT,
        FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO TEXT,
        VALOR_DEL_PROCEDIMIENTO TEXT,
        FOREIGN KEY (NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA) REFERENCES US(NUMERO_DE_IDENTIFICACION_DEL_USUARIO_DEL_SISTEMA)
);
