CREATE OR REPLACE FUNCTION create_new_registry_only_age(
    codigos_procedimientos TEXT[],
    edad_min INT,
    edad_max INT,
    unidad_edad TEXT
)
RETURNS TABLE (
    NUMERO_DE_LA_FACTURA TEXT,
    CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD TEXT,
    TIPO_DE_IDENTIFICACION_DEL_USUARIO TEXT,
    NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA TEXT,
    FECHA_DEL_PROCEDIMIENTO TEXT,
    NUMERO_DE_AUTORIZACION TEXT,
    CODIGO_DEL_PROCEDIMIENTO TEXT,
    AMBITO_DE_REALIZACION_DEL_PROCEDIMIENTO TEXT,
    FINALIDAD_DEL_PROCEDIMIENTO TEXT,
    PERSONAL_QUE_ATIENDE TEXT,
    DIAGNOSTICO_PRINCIPAL TEXT,
    DIAGNOSTICO_RELACIONADO TEXT,
    COMPLICACION TEXT,
    FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO TEXT,
    VALOR_DEL_PROCEDIMIENTO TEXT
) AS $$
DECLARE
    codigo_procedimiento TEXT;
BEGIN
    CREATE TEMP TABLE temp_ap AS TABLE AP WITH NO DATA;

    FOREACH codigo_procedimiento IN ARRAY codigos_procedimientos
    LOOP
        INSERT INTO temp_ap (
            NUMERO_DE_LA_FACTURA,
            CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD,
            TIPO_DE_IDENTIFICACION_DEL_USUARIO,
            NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA,
            FECHA_DEL_PROCEDIMIENTO,
            NUMERO_DE_AUTORIZACION,
            CODIGO_DEL_PROCEDIMIENTO,
            AMBITO_DE_REALIZACION_DEL_PROCEDIMIENTO,
            FINALIDAD_DEL_PROCEDIMIENTO,
            PERSONAL_QUE_ATIENDE,
            DIAGNOSTICO_PRINCIPAL,
            DIAGNOSTICO_RELACIONADO,
            COMPLICACION,
            FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO,
            VALOR_DEL_PROCEDIMIENTO
        )
        SELECT 
            AP.NUMERO_DE_LA_FACTURA,
            AP.CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD,
            AP.TIPO_DE_IDENTIFICACION_DEL_USUARIO,
            AP.NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA,
            AP.FECHA_DEL_PROCEDIMIENTO,
            AP.NUMERO_DE_AUTORIZACION,
            codigo_procedimiento AS CODIGO_DEL_PROCEDIMIENTO,
            AP.AMBITO_DE_REALIZACION_DEL_PROCEDIMIENTO,
            AP.FINALIDAD_DEL_PROCEDIMIENTO,
            AP.PERSONAL_QUE_ATIENDE,
            AP.DIAGNOSTICO_PRINCIPAL,
            AP.DIAGNOSTICO_RELACIONADO,
            AP.COMPLICACION,
            AP.FORMA_DE_REALIZACION_DEL_ACTO_QUIRURGICO,
            AP.VALOR_DEL_PROCEDIMIENTO
        FROM AP
        JOIN US ON AP.NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA = US.NUMERO_DE_IDENTIFICACION_DEL_USUARIO_DEL_SISTEMA
        WHERE CAST(US.EDAD AS INTEGER) BETWEEN edad_min AND edad_max
        AND US.UNIDAD_DE_MEDIDA_EN_LA_EDAD = unidad_edad;
    END LOOP;

    RETURN QUERY SELECT * FROM temp_ap;

    DROP TABLE temp_ap;
END;
$$ LANGUAGE plpgsql;