
CREATE TABLE AC (
                    NUMERO_DE_LA_FACTURA TEXT,
                    CODIGO_DEL_PRESTADOR_DE_SERVICIOS_DE_SALUD TEXT,
                    TIPO_DE_IDENTIFICACION_DEL_USUARIO TEXT,
                    NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA TEXT,
                    FECHA_DE_LA_CONSULTA TEXT,
                    NUMERO_DE_AUTORIZACION TEXT,
                    CODIGO_DE_LA_CONSULTA TEXT,
                    FINALIDAD_DE_LA_CAUSA_EXTERNA_CONSULTA TEXT,
                    CAUSA_EXTERNA TEXT,
                    CODIGO_DEL_DIAGNOSTICO_PRINCIPAL TEXT,
                    CODIGO_DEL_DIAGNOSTICO_RELACIONADO_NO_1 TEXT,
                    CODIGO_DEL_DIAGNOSTICO_RELACIONADO_NO_2 TEXT,
                    CODIGO_DEL_DIAGNOSTICO_RELACIONADO_NO_3 TEXT,
                    TIPO_DE_DIAGNOSTICO_PRINCIPAL TEXT,
                    VALOR_DE_LA_CONSULTA TEXT,
                    VALOR_DE_LA_CUOTA_MODERADORA TEXT,
                    VALOR_NETO_A_PAGAR TEXT,
                    FOREIGN KEY (NUMERO_DE_IDENTIFICACION_DEL_USUARIO_EN_EL_SISTEMA) REFERENCES US(NUMERO_DE_IDENTIFICACION_DEL_USUARIO_DEL_SISTEMA)
);

DELETE FROM AC;